spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
my:
  index:
    title: "spring clould admin"
  webfilter:
    enable: true

info:
  app:
    name: "spring clould admin"
  version: 0.1
eureka:
  client:
    enabled: true

management:
  endpoint:
    health:
      show-details=always: