version: '3'
services:
  mserviceadmin:
     privileged: true
     image: java
     container_name: mserviceadmin
     volumes:
        - $PWD/:/temp
        - /opt:/opt
        - /etc/hosts:/etc/hosts
        - /home/logs:/opt/logs
     networks:
        mynet:
          ipv4_address: 192.168.2.101
     command: java -jar /temp/mservice-admin-0.1.jar
networks:
  mynet:
    external: true
